name: Blocklet Developer Portal
title: Blocklet Developer Portal
description: This is Blocklet Developer Docs Site, powered by Blocklet Page
theme: docs
github: https://github.com/blocklet/blocklet-site
themeConfig:
  colors:
    primary: '#1DC1C7'
    secondary: '#F0FDFF'
  sidebar:
    en:
      - text: Introduction
        items:
          - text: Blocklet
            link: /introduction/blocklet
      - text: Prerequisites
        items:
          - text: DID Wallet
            link: /prerequisites/wallet
          - text: Blocklet Server
            link: /prerequisites/server
      - text: Develop Blocklet
        items:
          - text: Getting Started
            link: /development/getting-started
          - text: Blocklet Meta
            link: /development/blocklet-meta
          - text: Frontend-Only App
            link: /development/frontend-only-app
          - text: Fullstack App
            link: /development/fullstack-app
          - text: Blocklet Page App
            link: /development/blocklet-page-app
          - text: Composite App
            link: /development/composable-blocklet
          - text: User & Passports
            link: /development/user-and-passport
          - text: Notification
            link: /development/notification
          - text: Using Blocklet SDK
            link: /development/blocklet-sdk-usage
          - text: Using Blocklet UI
            link: /development/blocklet-ui-usage
      - text: 'Components In-Depth'
        items:
          - text: Core concepts
            link: /components/core-concepts
          - text: Develop a component
            link: /components/develop-component
          - text: Develop a composite app
            link: /components/develop-composite-app
      - text: Deployment
        items:
          - text: Bundle Blocklet
            link: /deployment/bundle
          - text: Deploy Blocklet To Blocklet Server
            link: /deployment/deploy
          - text: Publish Blocklet To Blocklet Store
            link: /deployment/upload
          - text: Using Github Actions
            link: /deployment/github-actions
      - text: Samples
        link: /samples
        items:
          - text: Simple HTML Demo
            link: /samples/simple-html-demo
          - text: 2048 Demo
            link: /samples/2048-demo
          - text: React Demo
            link: /samples/react-demo
          - text: Blocklet Page Demo
            link: /samples/blocklet-page-demo
          - text: Auth Demo
            link: /samples/auth-demo
          - text: Notification Demo
            link: /samples/notification-demo
          - text: Component Demo
            link: /samples/component-demo
          - text: DID Connect Demo
            link: /samples/did-connect-demo
      - text: API
        items:
          - text: Blocklet Meta
            link: /apis/blocklet-spec
          - text: Blocklet SDK
            link: /apis/blocklet-sdk
          - text: Blocklet CLI
            link: /apis/blocklet-cli
          - text: Blocklet UI
            link: /apis/blocklet-ui
          - text: Blocklet Actions
            link: /apis/blocklet-actions
          - text: Blocklet Page
            link: https://pages.blocklet.io/docs/intro
          - text: DID Connect
            link: https://www.didconnect.io/docs/intro
          - text: Create Blocklet
            link: https://www.createblocklet.dev/docs/intro
      - text: FAQ
        link: /faq
    zh:
      - text: 介绍
        items:
          - text: Blocklet
            link: /introduction/blocklet
      - text: 先决条件
        items:
          - text: DID Wallet
            link: /prerequisites/wallet
          - text: Blocklet Server
            link: /prerequisites/server
      - text: 开发 Blocklet
        items:
          - text: 入门
            link: /development/getting-started
          - text: Blocklet Meta
            link: /development/blocklet-meta
          - text: Frontend-Only App
            link: /development/frontend-only-app
          - text: Fullstack App
            link: /development/fullstack-app
          - text: Blocklet Page App
            link: /development/blocklet-page-app
          - text: Composite App
            link: /development/composable-blocklet
          - text: 用户和通行证
            link: /development/user-and-passport
          - text: 消息通知
            link: /development/notification
          - text: 使用 Blocklet SDK
            link: /development/blocklet-sdk-usage
          - text: 使用 Blocklet UI
            link: /development/blocklet-ui-usage
      - text: '深入组件'
        items:
          - text: Core concepts
            link: /components/core-concepts
          - text: Develop a component
            link: /components/develop-component
          - text: Develop a composite app
            link: /components/develop-composite-app
      - text: 部署
        items:
          - text: Bundle Blocklet
            link: /deployment/bundle
          - text: Deploy Blocklet To Blocklet Server
            link: /deployment/deploy
          - text: Publish Blocklet To Blocklet Store
            link: /deployment/upload
          - text: Using Github Actions
            link: /deployment/github-actions
      - text: 示例
        link: /samples
        items:
          - text: Simple HTML Demo
            link: /samples/simple-html-demo
          - text: 2048 Demo
            link: /samples/2048-demo
          - text: React Demo
            link: /samples/react-demo
          - text: Blocklet Page Demo
            link: /samples/blocklet-page-demo
          - text: Auth Demo
            link: /samples/auth-demo
          - text: Notification Demo
            link: /samples/notification-demo
          - text: Component Demo
            link: /samples/component-demo
          - text: DID Connect Demo
            link: /samples/did-connect-demo
      - text: API
        items:
          - text: Blocklet Meta
            link: /apis/blocklet-spec
          - text: Blocklet SDK
            link: /apis/blocklet-sdk
          - text: Blocklet CLI
            link: /apis/blocklet-cli
          - text: Blocklet UI
            link: /apis/blocklet-ui
          - text: Blocklet Actions
            link: /apis/blocklet-actions
          - text: Blocklet Page
            link: https://pages.blocklet.io/docs/intro
          - text: DID Connect
            link: https://www.didconnect.io/docs/intro
          - text: Create Blocklet
            link: https://www.createblocklet.dev/docs/intro
      - text: FAQ
        link: /faq
